---
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ImgScraper
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: "\z\z\x01"
